### ISSUE TITLE
Would you explain the details of Commits on Aug 22, 2023?

### ISSUE THREAD

**Issue by shamada-idec** [ezWheelSAS/swd-starter-kit-config#5]
I would like to know reason why files for 17pts were removed and the function of check_commissioning.py.
Would you explain the details?

**Comment by GMezWheel** [comment]
Hi @shamada-idec,

1) In fact, the 17pts directory has never been used because even on a StarterKit with a 17pts wiring, it was the 12pts commisioning that was applied.
2) The new check_commissioning.py file is used by the release procedure to control that the default StarterKit commissioning is well done.

**Comment by shamada-idec** [comment]
@GMezWheel 

Thank you for reply. I understand.
